/**
 * Created by sky on 2018/3/29.
 */
export const types = {
    //saga入门加减练习
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    ADD: 'ADD',
    CUT: 'CUT',
    ADD_IF_ODD:'ADD_IF_ODD',
    INCREMENT_IF_ODD: 'INCREMENT_IF_ODD',
    // 获取文章列表
    GET_ARTICLE_LIST: 'GET_ARTICLE_LIST',
    GET_ARTICLE_LIST_SUCCESS: 'GET_ARTICLE_LIST_SUCCESS',
    GET_ARTICLE_DETAIL:'GET_ARTICLE_DETAIL',
    GET_ARTICLE_DETAIL_SUCCESS:'GET_ARTICLE_DETAIL_SUCCESS',
    // 获取日志列表
    GET_LIFE_LIST:'GET_LIFE_LIST',
    GET_LIFE_LIST_SUCCESS:'GET_LIFE_LIST_SUCCESS',
    // 归档相关
    GET_ARCHIVE_LIST:'GET_ARCHIVE_LIST',
    GET_ARCHIVE_LIST_SUCCESS:'GET_ARCHIVE_LIST_SUCCESS'
}
