/**
 * Created by sky on 2018/3/29.
 */
export const types = {
    INCREMENT: 'INCREMENT',
    DECREMENT: 'DECREMENT',
    ADD: 'ADD',
    CUT: 'CUT',
    ADD_IF_ODD:'ADD_IF_ODD',
    INCREMENT_IF_ODD: 'INCREMENT_IF_ODD',
    GET_ARTICLE_LIST: 'GET_ARTICLE_LIST',
    GET_ARTICLE_ASYNC: 'GET_ARTICLE_ASYNC',
    GET_ARTICLE_LIST_SUCCESS: 'GET_ARTICLE_LIST_SUCCESS'
}
